name: Fusions

author: Luis Tohsaka

description: Fusionreactor for Slimefun.

main: me.tohsaka.fusions.Fusions

website: https://github.com/Isht4r/Fusions

depend: [Slimefun]

version: ${project.version}

api-version: 1.16
